-- Slice 2, Checkpoint C3 — Request response loop: submit, return, complete.
--
-- 05_DATA_MODEL_AND_API.md §4, §8, §12.3, §12.4, §13; 02_OPERATING_MODEL.md §4;
-- 06_BUILD_PLAN.md Slice 2 (checkpoints).
--
-- Additive to C1 (20260923120000) and C2 (20260925160000), which stay byte-for-byte
-- as committed:
--
--   1. `request_returns` — append-only: what Sollelio asks when it returns a Request
--      to the partner. One message, and one of two response types: `text` or
--      `approval`. Never extra `request_fields`: the published field definition is
--      not touched after publication.
--   2. Rounds on `request_submissions`: `return_id` (NULL for the initial round),
--      the returned round's own response in narrow columns, and `payload_hash` for
--      replay. One submission per round, as a unique index.
--   3. Append-only history, enforced by trigger for every role: submissions,
--      answers and returns are never updated.
--   4. `partner_request_returns` — the partner-facing columns of returns, built
--      like `partner_requests`. `partner_requests` itself is unchanged.
--   5. The three C3 commands, executable only by `service_role`. They authorize
--      the supplied actor explicitly: `auth.uid()` is empty in a service-role call.
--
-- Nothing here grants anon or authenticated any write.

-- ---------------------------------------------------------------------------
-- 0. Vocabulary and privileges the commands rely on
-- ---------------------------------------------------------------------------
create type public.request_return_response_type as enum ('text', 'approval');
create type public.request_approval_decision as enum ('approve', 'needs_changes');

-- The commands run as `service_role` (SECURITY INVOKER). Declared, not inherited,
-- as in C2. None of these reaches anon or authenticated.
grant select, insert on public.request_submissions to service_role;
grant select, insert on public.request_answers to service_role;
grant select on public.request_fields to service_role;

-- ---------------------------------------------------------------------------
-- 1. Returns
-- ---------------------------------------------------------------------------
-- `id` is generated by the staff client once per return attempt: it is the replay
-- identity (§13), so it has no default.
create table public.request_returns (
  id uuid primary key,
  request_id uuid not null references public.requests (id) on delete cascade,
  response_type public.request_return_response_type not null,
  message text not null
    check (message = btrim(message) and length(message) between 1 and 2000),
  created_by uuid not null references public.profiles (id) on delete restrict,
  created_at timestamptz not null default clock_timestamp()
);

comment on table public.request_returns is
  'Append-only. One precise new question or action per return (02_OPERATING_MODEL.md §4): '
  'a message and a response type (text | approval). Partners read it through '
  'partner_request_returns, never this table.';

create index request_returns_request_idx on public.request_returns (request_id, created_at);

alter table public.request_returns enable row level security;

revoke all on public.request_returns from public, anon, authenticated, service_role;
grant select on public.request_returns to authenticated;
grant select, insert on public.request_returns to service_role;

create policy request_returns_select_staff on public.request_returns
  for select to authenticated
  using (app.is_staff());

-- ---------------------------------------------------------------------------
-- 2. Rounds on submissions
-- ---------------------------------------------------------------------------
-- An initial-round submission answers the original fields in `request_answers`; a
-- returned-round submission answers only its return, in these columns, and has no
-- answers. `id` is the client's `submission_id` when written by `submit_request`.
alter table public.request_submissions
  add column return_id uuid references public.request_returns (id),
  add column response_text text,
  add column response_decision public.request_approval_decision,
  add column response_notes text,
  add column payload_hash text check (payload_hash ~ '^[0-9a-f]{32}$'),
  add constraint request_submissions_round_shape check (
    (return_id is null
       and response_text is null and response_decision is null and response_notes is null)
    or (return_id is not null and (
         (response_text is not null and response_decision is null and response_notes is null)
      or (response_text is null and response_decision is not null
          and (response_notes is null or response_decision = 'needs_changes'))))),
  add constraint request_submissions_response_text_length check (
    response_text is null
    or (response_text = btrim(response_text) and length(response_text) between 1 and 4000)),
  add constraint request_submissions_response_notes_length check (
    response_notes is null
    or (response_notes = btrim(response_notes) and length(response_notes) between 1 and 4000));

comment on column public.request_submissions.return_id is
  'The round this submission answers: NULL for the initial round, else the return.';

-- One submission per round: the initial round (NULL) counts once too.
create unique index request_submissions_one_per_round_idx
  on public.request_submissions (request_id, return_id) nulls not distinct;

create index request_submissions_return_idx on public.request_submissions (return_id)
  where return_id is not null;

-- The return must be this Request's, and the stored response must be the kind the
-- return asked for. A CHECK cannot consult another table, so this is a trigger.
create or replace function app.assert_request_submission_round()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  ret record;
begin
  if new.return_id is null then
    return new;
  end if;

  select request_id, response_type into ret from public.request_returns where id = new.return_id;
  if not found or ret.request_id <> new.request_id then
    raise exception 'A submission''s return must belong to the same Request.'
      using errcode = 'check_violation';
  end if;
  if (ret.response_type = 'text' and new.response_text is null)
     or (ret.response_type = 'approval' and new.response_decision is null) then
    raise exception 'A returned-round response must match the return''s response type.'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

revoke execute on function app.assert_request_submission_round() from public, anon, authenticated;

create trigger request_submissions_assert_round
  before insert on public.request_submissions
  for each row execute function app.assert_request_submission_round();

-- Only initial-round submissions carry answers to the original fields.
create or replace function app.assert_request_answer_initial_round()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if exists (select 1 from public.request_submissions s
              where s.id = new.submission_id and s.return_id is not null) then
    raise exception 'A returned-round submission has no answers to the original fields.'
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

revoke execute on function app.assert_request_answer_initial_round() from public, anon, authenticated;

create trigger request_answers_assert_initial_round
  before insert on public.request_answers
  for each row execute function app.assert_request_answer_initial_round();

-- History is appended, never rewritten — for every role, not only the API ones.
create or replace function app.reject_history_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception '% is append-only.', tg_table_name using errcode = 'check_violation';
end;
$$;

revoke execute on function app.reject_history_update() from public, anon, authenticated;

create trigger request_returns_append_only
  before update on public.request_returns
  for each row execute function app.reject_history_update();

create trigger request_submissions_append_only
  before update on public.request_submissions
  for each row execute function app.reject_history_update();

create trigger request_answers_append_only
  before update on public.request_answers
  for each row execute function app.reject_history_update();

-- ---------------------------------------------------------------------------
-- 3. Partner-facing returns
-- ---------------------------------------------------------------------------
-- Built like `partner_requests`: security_barrier, owned by postgres, security
-- invoker off, so the view's predicate governs. A return is visible exactly when its
-- Request is visible to the caller through `partner_requests`. `created_by` is not
-- part of the partner shape.
create view public.partner_request_returns
with (security_barrier = true)
as
select
  r.id,
  r.request_id,
  r.response_type,
  r.message,
  r.created_at
from public.request_returns r
where exists (select 1 from public.partner_requests pr where pr.id = r.request_id);

comment on view public.partner_request_returns is
  'Returns of the Requests the caller may see through partner_requests, without '
  'created_by (05_DATA_MODEL_AND_API.md §12.3).';

revoke all on public.partner_request_returns from public, anon, service_role;
grant select on public.partner_request_returns to authenticated;

-- ---------------------------------------------------------------------------
-- 4. Command helpers (internal; service_role only)
-- ---------------------------------------------------------------------------
-- New error, in the same RQ class as C2:
--   RQ012 stale_round — the round the partner answered is no longer the current one.

-- The replay identity of a submission payload: the round it claims to answer plus
-- the payload with answers ordered by field and strings trimmed. It is computed on
-- the payload as sent, so a retry of the same attempt always matches.
create or replace function app.request_submission_hash(p_expected_return_id uuid, p_payload jsonb)
returns text
language sql
immutable
set search_path = ''
as $$
  select md5(jsonb_build_object(
    'expected_return_id', p_expected_return_id,
    'payload', case
      when jsonb_typeof(p_payload -> 'answers') = 'array' then jsonb_build_object('answers', (
        select coalesce(jsonb_agg(jsonb_build_object(
                 'field_id', e ->> 'field_id',
                 'value', case when jsonb_typeof(e -> 'value') = 'string'
                               then to_jsonb(btrim(e ->> 'value')) else e -> 'value' end)
               order by e ->> 'field_id', (e -> 'value')::text), '[]'::jsonb)
          from jsonb_array_elements(p_payload -> 'answers') e))
      when jsonb_typeof(p_payload -> 'response') = 'object' then jsonb_build_object('response', (
        select coalesce(jsonb_object_agg(kv.key, case when jsonb_typeof(kv.value) = 'string'
                                                      then to_jsonb(btrim(kv.value #>> '{}')) else kv.value end),
                        '{}'::jsonb)
          from jsonb_each(p_payload -> 'response') kv))
      else p_payload
    end)::text);
$$;

revoke execute on function app.request_submission_hash(uuid, jsonb) from public, anon, authenticated;
grant execute on function app.request_submission_hash(uuid, jsonb) to service_role;

-- The Request's current return: the one without a submission. There is never more
-- than one (a return is only created once the previous round was answered).
create or replace function app.request_current_return(p_request uuid)
returns table (id uuid, response_type public.request_return_response_type)
language sql
stable
set search_path = ''
as $$
  select r.id, r.response_type
    from public.request_returns r
   where r.request_id = p_request
     and not exists (select 1 from public.request_submissions s where s.return_id = r.id)
   order by r.created_at desc
   limit 1;
$$;

revoke execute on function app.request_current_return(uuid) from public, anon, authenticated;
grant execute on function app.request_current_return(uuid) to service_role;

-- ---------------------------------------------------------------------------
-- 5. submit_request — the assigned partner answers the current round
-- ---------------------------------------------------------------------------
-- Lock order: Request (FOR UPDATE) → actor membership (FOR SHARE). The identity
-- lookup comes right after the Request lock and before any state check, so a retry
-- of a submission that already landed replays even though the Request has moved on,
-- and concurrent duplicates serialize on the Request row.
create or replace function public.cmd_submit_request(
  p_actor uuid, p_request_id uuid, p_submission_id uuid, p_expected_return_id uuid, p_payload jsonb)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  req record;
  existing record;
  cur record;
  errs jsonb := '[]'::jsonb;
  norm jsonb := '[]'::jsonb;
  item jsonb;
  resp jsonb;
  val jsonb;
  f record;
  idx integer := 0;
  seen uuid[] := '{}';
  fid uuid;
  k text;
  s text;
  path text;
  decision text;
  r_text text;
  r_decision text;
  r_notes text;
  hash text;
  submitted timestamptz;
  rev integer;
begin
  if p_submission_id is null then
    perform app.request_fail('RQ003', 'validation_failed', jsonb_build_object('errors', jsonb_build_array(
      app.request_err('submission_id', 'required', 'Falta o identificador da resposta.'))));
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    perform app.request_fail('RQ003', 'validation_failed', jsonb_build_object('errors', jsonb_build_array(
      app.request_err('payload', 'invalid', 'Resposta inválida.'))));
  end if;

  select id, organization_id, status, assignee_profile_id, published_at
    into req from public.requests where id = p_request_id for update;
  if not found then
    perform app.request_fail('RQ002', 'not_found', jsonb_build_object('entity', 'request'));
  end if;

  -- Identity first: the same attempt replays its original outcome, whatever the
  -- Request's state is now. Anything else under this id is a conflict.
  select id, request_id, submitted_by, return_id, payload_hash, created_at
    into existing from public.request_submissions where id = p_submission_id;
  if found then
    if existing.request_id = p_request_id and existing.submitted_by = p_actor
       and existing.payload_hash = app.request_submission_hash(p_expected_return_id, p_payload) then
      select (e.metadata ->> 'revision')::integer into rev
        from public.activity_events e
       where e.object_type = 'request' and e.object_id = p_request_id
         and e.event_type = 'request.submitted' and e.metadata ->> 'submission_id' = p_submission_id::text;
      return jsonb_build_object('request_id', p_request_id, 'submission_id', p_submission_id,
                                'return_id', existing.return_id, 'status', 'needs_sollelio',
                                'revision', rev, 'submitted_at', existing.created_at, 'replayed', true);
    end if;
    perform app.request_fail('RQ010', 'idempotency_conflict');
  end if;

  -- Authorization of the supplied actor. Everything the partner may not see looks
  -- the same: not found.
  if p_actor is null or req.published_at is null or req.assignee_profile_id is distinct from p_actor then
    perform app.request_fail('RQ002', 'not_found', jsonb_build_object('entity', 'request'));
  end if;
  perform 1 from public.organization_memberships m
   where m.organization_id = req.organization_id and m.profile_id = p_actor and m.status = 'active'
   for share;
  if not found then
    perform app.request_fail('RQ002', 'not_found', jsonb_build_object('entity', 'request'));
  end if;

  if req.status <> 'needs_partner' then
    perform app.request_fail('RQ009', 'invalid_state');
  end if;

  select c.id, c.response_type into cur from app.request_current_return(p_request_id) c;
  if cur.id is distinct from p_expected_return_id then
    perform app.request_fail('RQ012', 'stale_round', jsonb_build_object('current_return_id', cur.id));
  end if;

  for k in select jsonb_object_keys(p_payload) loop
    if not (k = any (array['answers', 'response'])) then
      errs := errs || app.request_err(k, 'unknown_field', 'Campo não reconhecido.');
    end if;
  end loop;

  if cur.id is null then
    -- Initial round: the original fields, validated as a whole.
    if p_payload ? 'response' then
      errs := errs || app.request_err('response', 'not_allowed', 'Esta resposta é às perguntas do pedido.');
    end if;
    if jsonb_typeof(p_payload -> 'answers') is distinct from 'array' then
      errs := errs || app.request_err('answers', 'invalid', 'Respostas inválidas.');
    else
      for item in select value from jsonb_array_elements(p_payload -> 'answers') loop
        path := format('answers[%s]', idx);
        idx := idx + 1;
        if jsonb_typeof(item) <> 'object' then
          errs := errs || app.request_err(path, 'invalid', 'Resposta inválida.');
          continue;
        end if;
        for k in select jsonb_object_keys(item) loop
          if not (k = any (array['field_id', 'value'])) then
            errs := errs || app.request_err(path || '.' || k, 'unknown_field', 'Campo não reconhecido.');
          end if;
        end loop;

        fid := null;
        if jsonb_typeof(item -> 'field_id') = 'string'
           and (item ->> 'field_id') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
          fid := (item ->> 'field_id')::uuid;
        end if;
        if fid is null then
          errs := errs || app.request_err(path || '.field_id', 'invalid', 'Pergunta inválida.');
          continue;
        end if;

        select id, type, options, key, system_generated into f
          from public.request_fields where id = fid and request_id = p_request_id;
        if not found then
          errs := errs || app.request_err('answers.' || fid, 'unknown_field', 'Esta pergunta não pertence a este pedido.');
          continue;
        end if;
        if fid = any (seen) then
          errs := errs || app.request_err('answers.' || fid, 'duplicate', 'Esta pergunta foi respondida mais de uma vez.');
          continue;
        end if;
        seen := seen || fid;

        path := 'answers.' || fid;
        val := item -> 'value';
        if val is null or jsonb_typeof(val) = 'null' then
          continue;  -- not answered
        end if;

        case f.type
          when 'long_text' then
            if jsonb_typeof(val) <> 'string' then
              errs := errs || app.request_err(path, 'invalid_type', 'Escreva a resposta em texto.');
            else
              s := btrim(val #>> '{}');
              if s = '' then
                continue;  -- empty after trimming: not answered
              elsif length(s) > 4000 then
                errs := errs || app.request_err(path, 'too_long', 'No máximo 4000 caracteres.');
              else
                norm := norm || jsonb_build_array(jsonb_build_object('field_id', fid, 'value', to_jsonb(s)));
              end if;
            end if;
          when 'boolean' then
            if jsonb_typeof(val) <> 'boolean' then
              errs := errs || app.request_err(path, 'invalid_type', 'Responda sim ou não.');
            else
              norm := norm || jsonb_build_array(jsonb_build_object('field_id', fid, 'value', val));
            end if;
          when 'single_choice' then
            if jsonb_typeof(val) <> 'string' then
              errs := errs || app.request_err(path, 'invalid_type', 'Escolha uma das opções.');
            elsif not exists (select 1 from jsonb_array_elements_text(coalesce(f.options, '[]'::jsonb)) o
                               where o = btrim(val #>> '{}')) then
              errs := errs || app.request_err(path, 'invalid_option', 'Escolha uma das opções.');
            else
              norm := norm || jsonb_build_array(jsonb_build_object('field_id', fid, 'value', to_jsonb(btrim(val #>> '{}'))));
            end if;
          when 'approval' then
            if jsonb_typeof(val) <> 'string' then
              errs := errs || app.request_err(path, 'invalid_type', 'Escolha Aprovar ou Precisa de alterações.');
            elsif (val #>> '{}') not in ('approve', 'needs_changes') then
              errs := errs || app.request_err(path, 'invalid_option', 'Escolha Aprovar ou Precisa de alterações.');
            else
              decision := val #>> '{}';
              norm := norm || jsonb_build_array(jsonb_build_object('field_id', fid, 'value', val));
            end if;
        end case;
      end loop;

      -- Every required field answered. `false` is an answer.
      for f in select id from public.request_fields
                where request_id = p_request_id and required order by sort_order loop
        if not exists (select 1 from jsonb_array_elements(norm) e where e ->> 'field_id' = f.id::text)
           and not exists (select 1 from jsonb_array_elements(errs) x where x ->> 'field' = 'answers.' || f.id) then
          errs := errs || app.request_err('answers.' || f.id, 'required', 'Responda a esta pergunta.');
        end if;
      end loop;

      -- Change notes belong to "needs changes" only.
      if decision = 'approve' then
        for f in select id from public.request_fields
                  where request_id = p_request_id and system_generated and key = 'approval_notes' loop
          if exists (select 1 from jsonb_array_elements(norm) e where e ->> 'field_id' = f.id::text) then
            errs := errs || app.request_err('answers.' || f.id, 'notes_not_allowed',
              'As notas de alteração só se enviam com “Precisa de alterações”.');
          end if;
        end loop;
      end if;
    end if;
  else
    -- Returned round: only the return's own question.
    if p_payload ? 'answers' then
      errs := errs || app.request_err('answers', 'not_allowed', 'Esta resposta é só à pergunta da Sollelio.');
    end if;
    resp := p_payload -> 'response';
    if jsonb_typeof(resp) is distinct from 'object' then
      errs := errs || app.request_err('response', 'invalid', 'Resposta inválida.');
    elsif cur.response_type = 'text' then
      for k in select jsonb_object_keys(resp) loop
        if k <> 'text' then
          errs := errs || app.request_err('response.' || k, 'unknown_field', 'Campo não reconhecido.');
        end if;
      end loop;
      if jsonb_typeof(resp -> 'text') is distinct from 'string' then
        errs := errs || app.request_err('response.text', 'required', 'Escreva a sua resposta.');
      else
        r_text := btrim(resp ->> 'text');
        if r_text = '' then
          errs := errs || app.request_err('response.text', 'required', 'Escreva a sua resposta.');
        elsif length(r_text) > 4000 then
          errs := errs || app.request_err('response.text', 'too_long', 'No máximo 4000 caracteres.');
        end if;
      end if;
    else
      for k in select jsonb_object_keys(resp) loop
        if not (k = any (array['decision', 'notes'])) then
          errs := errs || app.request_err('response.' || k, 'unknown_field', 'Campo não reconhecido.');
        end if;
      end loop;
      if jsonb_typeof(resp -> 'decision') is distinct from 'string'
         or (resp ->> 'decision') not in ('approve', 'needs_changes') then
        errs := errs || app.request_err('response.decision', 'required', 'Escolha Aprovar ou Precisa de alterações.');
      else
        r_decision := resp ->> 'decision';
      end if;
      if resp ? 'notes' and jsonb_typeof(resp -> 'notes') <> 'null' then
        if jsonb_typeof(resp -> 'notes') <> 'string' then
          errs := errs || app.request_err('response.notes', 'invalid_type', 'Escreva as notas em texto.');
        else
          r_notes := nullif(btrim(resp ->> 'notes'), '');
          if length(r_notes) > 4000 then
            errs := errs || app.request_err('response.notes', 'too_long', 'No máximo 4000 caracteres.');
          elsif r_notes is not null and r_decision = 'approve' then
            errs := errs || app.request_err('response.notes', 'notes_not_allowed',
              'As notas de alteração só se enviam com “Precisa de alterações”.');
          end if;
        end if;
      end if;
    end if;
  end if;

  if jsonb_array_length(errs) > 0 then
    perform app.request_fail('RQ003', 'validation_failed', jsonb_build_object('errors', errs));
  end if;

  hash := app.request_submission_hash(p_expected_return_id, p_payload);
  submitted := clock_timestamp();

  insert into public.request_submissions
    (id, request_id, submitted_by, source, return_id, response_text, response_decision, response_notes,
     payload_hash, created_at)
  values
    (p_submission_id, p_request_id, p_actor, 'partner_os', cur.id, r_text,
     r_decision::public.request_approval_decision, r_notes, hash, submitted);

  insert into public.request_answers (submission_id, request_field_id, value)
  select p_submission_id, (e ->> 'field_id')::uuid, e -> 'value'
    from jsonb_array_elements(norm) e;

  update public.requests set status = 'needs_sollelio', next_actor = 'sollelio' where id = p_request_id;
  select revision into rev from public.requests where id = p_request_id;

  insert into public.activity_events (organization_id, actor_profile_id, event_type, object_type, object_id, metadata)
  values (req.organization_id, p_actor, 'request.submitted', 'request', p_request_id,
          jsonb_build_object('submission_id', p_submission_id, 'return_id', cur.id, 'revision', rev));

  return jsonb_build_object('request_id', p_request_id, 'submission_id', p_submission_id, 'return_id', cur.id,
                            'status', 'needs_sollelio', 'revision', rev, 'submitted_at', submitted,
                            'replayed', false);
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. return_request_to_partner — one precise new question or action
-- ---------------------------------------------------------------------------
-- Lock order: Request (FOR UPDATE) → organization → assignee membership (FOR SHARE),
-- the C2 order. The return id is the replay identity, looked up after the lock.
create or replace function public.cmd_return_request_to_partner(
  p_actor uuid, p_request_id uuid, p_return_id uuid, p_expected_revision integer,
  p_response_type text, p_message text)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  req record;
  existing record;
  errs jsonb := '[]'::jsonb;
  msg text := btrim(coalesce(p_message, ''));
  org_status public.organization_status;
  returned timestamptz;
  rev integer;
begin
  perform app.request_require_staff(p_actor);

  if p_return_id is null then
    perform app.request_fail('RQ003', 'validation_failed', jsonb_build_object('errors', jsonb_build_array(
      app.request_err('return_id', 'required', 'Falta o identificador da devolução.'))));
  end if;

  select id, organization_id, status, revision, assignee_profile_id
    into req from public.requests where id = p_request_id for update;
  if not found then
    perform app.request_fail('RQ002', 'not_found', jsonb_build_object('entity', 'request'));
  end if;

  select id, request_id, response_type, message, created_by, created_at
    into existing from public.request_returns where id = p_return_id;
  if found then
    if existing.request_id = p_request_id and existing.created_by = p_actor
       and existing.response_type::text = p_response_type and existing.message = msg then
      select (e.metadata ->> 'revision')::integer into rev
        from public.activity_events e
       where e.object_type = 'request' and e.object_id = p_request_id
         and e.event_type = 'request.returned_to_partner' and e.metadata ->> 'return_id' = p_return_id::text;
      return jsonb_build_object('request_id', p_request_id, 'return_id', p_return_id,
                                'response_type', existing.response_type, 'status', 'needs_partner',
                                'revision', rev, 'returned_at', existing.created_at, 'replayed', true);
    end if;
    perform app.request_fail('RQ010', 'idempotency_conflict');
  end if;

  if req.status <> 'needs_sollelio' then
    perform app.request_fail('RQ009', 'invalid_state', jsonb_build_object('status', req.status));
  end if;
  if p_expected_revision is null or req.revision <> p_expected_revision then
    perform app.request_fail('RQ008', 'stale_revision', jsonb_build_object('current_revision', req.revision));
  end if;

  if p_response_type is null or p_response_type not in ('text', 'approval') then
    errs := errs || app.request_err('response_type', 'required', 'Escolha o tipo de resposta: texto ou aprovação.');
  end if;
  if msg = '' then
    errs := errs || app.request_err('message', 'required', 'Escreva o que falta, para a parceira ler.');
  elsif length(msg) > 2000 then
    errs := errs || app.request_err('message', 'too_long', 'No máximo 2000 caracteres.');
  end if;
  if jsonb_array_length(errs) > 0 then
    perform app.request_fail('RQ003', 'validation_failed', jsonb_build_object('errors', errs));
  end if;

  -- A Request never waits on nobody: the organization and the assignee's
  -- membership must still be active.
  select o.status into org_status from public.organizations o where o.id = req.organization_id for share;
  if org_status is distinct from 'active' then
    perform app.request_fail('RQ004', 'organization_not_active', jsonb_build_object('status', org_status));
  end if;
  perform 1 from public.organization_memberships m
   where m.organization_id = req.organization_id and m.profile_id = req.assignee_profile_id
     and m.status = 'active'
   for share;
  if not found then
    perform app.request_fail('RQ005', 'assignee_not_active_member');
  end if;

  returned := clock_timestamp();
  insert into public.request_returns (id, request_id, response_type, message, created_by, created_at)
  values (p_return_id, p_request_id, p_response_type::public.request_return_response_type, msg, p_actor, returned);

  update public.requests set status = 'needs_partner', next_actor = 'partner' where id = p_request_id;
  select revision into rev from public.requests where id = p_request_id;

  insert into public.activity_events (organization_id, actor_profile_id, event_type, object_type, object_id, metadata)
  values (req.organization_id, p_actor, 'request.returned_to_partner', 'request', p_request_id,
          jsonb_build_object('return_id', p_return_id, 'response_type', p_response_type, 'revision', rev));

  return jsonb_build_object('request_id', p_request_id, 'return_id', p_return_id,
                            'response_type', p_response_type, 'status', 'needs_partner',
                            'revision', rev, 'returned_at', returned, 'replayed', false);
end;
$$;

-- ---------------------------------------------------------------------------
-- 7. complete_request — Sollelio closes a Request the partner answered
-- ---------------------------------------------------------------------------
-- No key: a retried completion is `invalid_state`, and the client settles an
-- ambiguous one by reading the Request.
create or replace function public.cmd_complete_request(
  p_actor uuid, p_request_id uuid, p_expected_revision integer)
returns jsonb
language plpgsql
set search_path = ''
as $$
declare
  req record;
  completed timestamptz;
  rev integer;
begin
  perform app.request_require_staff(p_actor);

  select id, organization_id, status, revision
    into req from public.requests where id = p_request_id for update;
  if not found then
    perform app.request_fail('RQ002', 'not_found', jsonb_build_object('entity', 'request'));
  end if;
  if req.status <> 'needs_sollelio' then
    perform app.request_fail('RQ009', 'invalid_state', jsonb_build_object('status', req.status));
  end if;
  if p_expected_revision is null or req.revision <> p_expected_revision then
    perform app.request_fail('RQ008', 'stale_revision', jsonb_build_object('current_revision', req.revision));
  end if;

  completed := now();
  update public.requests
     set status = 'completed', next_actor = 'none', completed_at = completed
   where id = p_request_id;
  select revision into rev from public.requests where id = p_request_id;

  insert into public.activity_events (organization_id, actor_profile_id, event_type, object_type, object_id, metadata)
  values (req.organization_id, p_actor, 'request.completed', 'request', p_request_id,
          jsonb_build_object('revision', rev));

  return jsonb_build_object('request_id', p_request_id, 'status', 'completed', 'revision', rev,
                            'completed_at', completed);
end;
$$;

revoke execute on function public.cmd_submit_request(uuid, uuid, uuid, uuid, jsonb) from public, anon, authenticated;
revoke execute on function public.cmd_return_request_to_partner(uuid, uuid, uuid, integer, text, text) from public, anon, authenticated;
revoke execute on function public.cmd_complete_request(uuid, uuid, integer) from public, anon, authenticated;
grant execute on function public.cmd_submit_request(uuid, uuid, uuid, uuid, jsonb) to service_role;
grant execute on function public.cmd_return_request_to_partner(uuid, uuid, uuid, integer, text, text) to service_role;
grant execute on function public.cmd_complete_request(uuid, uuid, integer) to service_role;
